development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: image_processor
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: image_processor
  pool: 5
  username: root
  password:

